### ISSUE TITLE
Submitting a resource with an error causes permanent link field to be highlighted

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/coop-library-framework#155]
**Describe the bug**
When submitting a resource with an error (i.e. a missing publication year, or invalid URL for Publisher link), causes the Permanent Link field will become highlighted in red (as though it has an error) even though the value of the permanent link field may be valid.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new resource
2. Fill in the Permanent Link field with a valid URL (i.e. `google.com`).
3. Leave Publication year blank, or fill in `foo` for Publisher Link.
4. Submit the form.
5. Notice an error message appears for the publication year, and the Permanent Link field is highlighted in red.

**Expected behaviour**
If there are errors on the form, and the Permanent Link field is valid, then the Permanent Link field should not appear with error highlighting.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69.0.3

**Comment by greatislander** [comment]
@jhung is this with the dev branch?

**Comment by greatislander** [comment]
Fixed in #129.
