### ISSUE TITLE
Spec thumbnail selection

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-library-framework#4]

**Comment by jhung** [comment]
Scenario - when a user adds a resource, it may be desirable to have a visual representation of that resource (thumbnail image) appear alongside.

Explore different ways to programatically generate a thumbnail for a resource URL:
* Randomly generated thumbnail using SVG
* Scrape the resource and produce a thumbnail based on rendered page, or found images / media
* Upload an image
* other?

There should be considerations for low-bandwidth mobile situations.

Lower priority - there's no clear design requirement for this at the moment.
