### ISSUE TITLE
Spec license selection

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-library-framework#5]

**Comment by jhung** [comment]
Created a wiki doc for license research: https://wiki.fluidproject.org/display/fluid/Learning+Commons+Resources+License+Selection+Research

**Comment by greatislander** [comment]
Breakdown of licenses in the existing 732 unique resources:

| License     | Resources |
| ----------- | --------- |
| Copyright   | 8         |
| CC-BY-ND    | 1         |
| CC-BY-SA    | 1         |
| CC-BY-NC-SA | 3         |

I propose we add the following options:

- All Rights Reserved
- [CC-BY](https://creativecommons.org/licenses/by/4.0)
- [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0)
- [CC-BY-ND](https://creativecommons.org/licenses/by-nd/4.0)
- [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0)
- [CC-BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0)
- [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0)
- [ECL](https://opensource.org/licenses/ECL-2.0)
- [No Rights Reserved](https://creativecommons.org/share-your-work/public-domain/cc0/) (aka CC0)
- [No Known Copyright](https://creativecommons.org/share-your-work/public-domain/pdm/)

In addition, we should add a field for a custom license statement.
