### ISSUE TITLE
String location reference in POT file not accurate

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/coop-library-framework#54]
**Describe the bug**
String location references in `languages/learning-commons-framework.pot` do not reference the correct locations in `functions/metadata.php`.

**To Reproduce**
Example `languages/learning-commons-framework.pot:89`:
```
#: includes/functions/core.php:161
msgid "Are you sure you want to remove this revision?"
```

**Expected behavior**
Example `languages/learning-commons-framework.pot:89`:
```
#: includes/functions/metadata.php:238
msgid "Are you sure you want to remove this revision?"
```
Changed `core.php:161` to `metadata.php:238`.

**Comment by greatislander** [comment]
Resolved by #82 — we can now directly localize the plugin strings via the WordPress dashboard. We still need to remove the `.pot` file though.
