### ISSUE TITLE
Spec resource archiving features

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-library-framework#6]

**Comment by jhung** [comment]
Documented research into Perma.cc and Archive.org on this wiki page:
https://wiki.fluidproject.org/display/fluid/Resource+preservation+research

My suggestion for an initial pass at this feature is to add the ability to input multiple Perma.cc or Archive.org links with the resource.

**Comment by greatislander** [comment]
I'm going to close this in lieu of the issue you just opened (#72) to add the link fields @jhung. Thanks for all your detailed work on this!
